# Generated by Django 2.2.9 on 2020-01-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.TextField()),
                ('query', models.TextField()),
                ('positive_percentage', models.IntegerField(default=0)),
                ('neutral_percentage', models.IntegerField(default=0)),
                ('negative_percentage', models.IntegerField(default=0)),
                ('total_tweet_volume', models.TextField(default='0')),
                ('is_top_trending', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.TextField()),
                ('text', models.TextField()),
                ('retweet_count', models.TextField()),
                ('favourite_count', models.TextField()),
                ('oembed_html', models.TextField()),
                ('compund_value', models.IntegerField(default=0)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.Trend')),
            ],
        ),
    ]
