# Generated by Django 2.2.9 on 2020-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
