# Generated by Django 2.2.9 on 2020-02-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='oembed_html',
        ),
    ]
