# Generated by Django 2.2.9 on 2020-01-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_log_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='compund_value',
            new_name='compound_value',
        ),
    ]
