# Generated by Django 2.2.9 on 2020-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0003_auto_20200125_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
