# Generated by Django 2.2.9 on 2020-01-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_auto_20200125_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='negative_percentage',
            new_name='num_negative',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='neutral_percentage',
            new_name='num_neutral',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='positive_percentage',
            new_name='num_positive',
        ),
    ]
