# Generated by Django 2.2.9 on 2020-01-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_auto_20200127_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.TextField(unique=True),
        ),
    ]
