# Generated by Django 2.2.9 on 2020-01-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_auto_20200127_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_id',
            new_name='id_str',
        ),
    ]
